const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yP9ZK7QWL._AC_UX575_.jpg",
    title: "Nike Air Force 1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(389 reviews)",
    prevPrice: "$130,00",
    newPrice: "99",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71lX6R7xXVL._AC_UX575_.jpg",
    title: "Nike Air Max 270",
    star: <AiFillStar className="rating-star" />,
    reviews: "(245 reviews)",
    prevPrice: "$180,00",
    newPrice: "129",
    company: "Nike",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71K0zQmJY7L._AC_UX575_.jpg",
    title: "Nike Revolution 6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(198 reviews)",
    prevPrice: "$95,00",
    newPrice: "69",
    company: "Nike",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71J5W8YQWDL._AC_UX575_.jpg",
    title: "Nike Court Vision Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(276 reviews)",
    prevPrice: "$110,00",
    newPrice: "79",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71F5Qm8ZQVL._AC_UX575_.jpg",
    title: "Nike Dunk Low Retro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(421 reviews)",
    prevPrice: "$160,00",
    newPrice: "119",
    company: "Nike",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71A8M5XQZBL._AC_UX575_.jpg",
    title: "Nike Air Zoom Pegasus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(315 reviews)",
    prevPrice: "$150,00",
    newPrice: "109",
    company: "Nike",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71N8QX7M5VL._AC_UX575_.jpg",
    title: "Nike Blazer Mid '77",
    star: <AiFillStar className="rating-star" />,
    reviews: "(287 reviews)",
    prevPrice: "$125,00",
    newPrice: "89",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71P7Q8MXLBL._AC_UX575_.jpg",
    title: "Nike Air Max SC",
    star: <AiFillStar className="rating-star" />,
    reviews: "(176 reviews)",
    prevPrice: "$120,00",
    newPrice: "85",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Q8M7XPLVL._AC_UX575_.jpg",
    title: "Nike Downshifter 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "(154 reviews)",
    prevPrice: "$100,00",
    newPrice: "72",
    company: "Nike",
    color: "green",
    category: "running",
  },

  {
    img: "https://m.media-amazon.com/images/I/71T3K9ZQWBL._AC_UX575_.jpg",
    title: "Adidas Ultraboost 22",
    star: <AiFillStar className="rating-star" />,
    reviews: "(287 reviews)",
    prevPrice: "$180,00",
    newPrice: "129",
    company: "Adidas",
    color: "white",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Y8K2XQMVL._AC_UX575_.jpg",
    title: "Adidas Superstar",
    star: <AiFillStar className="rating-star" />,
    reviews: "(512 reviews)",
    prevPrice: "$120,00",
    newPrice: "89",
    company: "Adidas",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71H7Q5ZMXBL._AC_UX575_.jpg",
    title: "Adidas Forum Low",
    star: <AiFillStar className="rating-star" />,
    reviews: "(267 reviews)",
    prevPrice: "$130,00",
    newPrice: "95",
    company: "Adidas",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71L5X8QZMVL._AC_UX575_.jpg",
    title: "Adidas Gazelle",
    star: <AiFillStar className="rating-star" />,
    reviews: "(349 reviews)",
    prevPrice: "$125,00",
    newPrice: "92",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71M8Q2XKZBL._AC_UX575_.jpg",
    title: "Adidas Runfalcon 3.0",
    star: <AiFillStar className="rating-star" />,
    reviews: "(198 reviews)",
    prevPrice: "$90,00",
    newPrice: "65",
    company: "Adidas",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71P4X8ZQWVL._AC_UX575_.jpg",
    title: "Adidas Duramo SL",
    star: <AiFillStar className="rating-star" />,
    reviews: "(231 reviews)",
    prevPrice: "$85,00",
    newPrice: "59",
    company: "Adidas",
    color: "grey",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71R8Q5XMVBL._AC_UX575_.jpg",
    title: "Adidas NMD R1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(398 reviews)",
    prevPrice: "$170,00",
    newPrice: "119",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71S7X2QZKVL._AC_UX575_.jpg",
    title: "Adidas Lite Racer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(167 reviews)",
    prevPrice: "$80,00",
    newPrice: "55",
    company: "Adidas",
    color: "navy",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71V5Q8ZMXBL._AC_UX575_.jpg",
    title: "Adidas Alphabounce",
    star: <AiFillStar className="rating-star" />,
    reviews: "(289 reviews)",
    prevPrice: "$135,00",
    newPrice: "99",
    company: "Adidas",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71W8K5XQZVL._AC_UX575_.jpg",
    title: "Adidas Continental 80",
    star: <AiFillStar className="rating-star" />,
    reviews: "(215 reviews)",
    prevPrice: "$115,00",
    newPrice: "82",
    company: "Adidas",
    color: "white",
    category: "casual",
  },

  {
    img: "https://m.media-amazon.com/images/I/71X5Q8ZMLBL._AC_UX575_.jpg",
    title: "Puma RS-X Reinvention",
    star: <AiFillStar className="rating-star" />,
    reviews: "(198 reviews)",
    prevPrice: "$130,00",
    newPrice: "89",
    company: "Puma",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Z7Q2XMVBL._AC_UX575_.jpg",
    title: "Puma Suede Classic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(312 reviews)",
    prevPrice: "$100,00",
    newPrice: "69",
    company: "Puma",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71A5X8QZKVL._AC_UX575_.jpg",
    title: "Puma Caven 2.0",
    star: <AiFillStar className="rating-star" />,
    reviews: "(143 reviews)",
    prevPrice: "$90,00",
    newPrice: "59",
    company: "Puma",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71B8Q5XMVBL._AC_UX575_.jpg",
    title: "Puma Velocity Nitro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(249 reviews)",
    prevPrice: "$145,00",
    newPrice: "99",
    company: "Puma",
    color: "orange",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71C7X2QZKVL._AC_UX575_.jpg",
    title: "Puma Slipstream",
    star: <AiFillStar className="rating-star" />,
    reviews: "(195 reviews)",
    prevPrice: "$125,00",
    newPrice: "89",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71D5Q8ZMXBL._AC_UX575_.jpg",
    title: "Puma Smash v2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(314 reviews)",
    prevPrice: "$75,00",
    newPrice: "49",
    company: "Puma",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E8X5QZLVL._AC_UX575_.jpg",
    title: "Puma RS 3.0",
    star: <AiFillStar className="rating-star" />,
    reviews: "(211 reviews)",
    prevPrice: "$120,00",
    newPrice: "85",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71F7Q2XMKBL._AC_UX575_.jpg",
    title: "Puma Future Rider",
    star: <AiFillStar className="rating-star" />,
    reviews: "(274 reviews)",
    prevPrice: "$110,00",
    newPrice: "79",
    company: "Puma",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71G5X8QZMVL._AC_UX575_.jpg",
    title: "Puma Electrify Nitro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(186 reviews)",
    prevPrice: "$115,00",
    newPrice: "79",
    company: "Puma",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71H8Q5XKZBL._AC_UX575_.jpg",
    title: "Puma Anzarun Lite",
    star: <AiFillStar className="rating-star" />,
    reviews: "(154 reviews)",
    prevPrice: "$85,00",
    newPrice: "59",
    company: "Puma",
    color: "grey",
    category: "running",
  },

  {
    img: "https://m.media-amazon.com/images/I/71J7X2QZMVL._AC_UX575_.jpg",
    title: "New Balance 574 Classic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(412 reviews)",
    prevPrice: "$130,00",
    newPrice: "95",
    company: "New Balance",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71K5Q8XZMBl._AC_UX575_.jpg",
    title: "New Balance 550",
    star: <AiFillStar className="rating-star" />,
    reviews: "(573 reviews)",
    prevPrice: "$140,00",
    newPrice: "99",
    company: "New Balance",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71L8X5QZKVL._AC_UX575_.jpg",
    title: "New Balance 327",
    star: <AiFillStar className="rating-star" />,
    reviews: "(298 reviews)",
    prevPrice: "$135,00",
    newPrice: "95",
    company: "New Balance",
    color: "cream",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71M7Q2XMVBL._AC_UX575_.jpg",
    title: "New Balance Fresh Foam 1080",
    star: <AiFillStar className="rating-star" />,
    reviews: "(354 reviews)",
    prevPrice: "$165,00",
    newPrice: "119",
    company: "New Balance",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71N5X8QZLVL._AC_UX575_.jpg",
    title: "New Balance Fresh Foam 680",
    star: <AiFillStar className="rating-star" />,
    reviews: "(264 reviews)",
    prevPrice: "$110,00",
    newPrice: "79",
    company: "New Balance",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71P8Q5XMKBL._AC_UX575_.jpg",
    title: "New Balance 530",
    star: <AiFillStar className="rating-star" />,
    reviews: "(389 reviews)",
    prevPrice: "$125,00",
    newPrice: "89",
    company: "New Balance",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Q7X2QZMVL._AC_UX575_.jpg",
    title: "New Balance 2002R",
    star: <AiFillStar className="rating-star" />,
    reviews: "(431 reviews)",
    prevPrice: "$160,00",
    newPrice: "119",
    company: "New Balance",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71R5Q8XZMBl._AC_UX575_.jpg",
    title: "New Balance 860",
    star: <AiFillStar className="rating-star" />,
    reviews: "(217 reviews)",
    prevPrice: "$140,00",
    newPrice: "99",
    company: "New Balance",
    color: "navy",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71S8X5QZKVL._AC_UX575_.jpg",
    title: "New Balance 990v5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(356 reviews)",
    prevPrice: "$190,00",
    newPrice: "149",
    company: "New Balance",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71T7Q2XMVBL._AC_UX575_.jpg",
    title: "New Balance 515",
    star: <AiFillStar className="rating-star" />,
    reviews: "(189 reviews)",
    prevPrice: "$100,00",
    newPrice: "69",
    company: "New Balance",
    color: "blue",
    category: "casual",
  },

  {
    img: "https://m.media-amazon.com/images/I/71V5X8QZLML._AC_UX575_.jpg",
    title: "Reebok Club C 85",
    star: <AiFillStar className="rating-star" />,
    reviews: "(231 reviews)",
    prevPrice: "$105,00",
    newPrice: "75",
    company: "Reebok",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71W8Q5XMKBL._AC_UX575_.jpg",
    title: "Reebok Classic Leather",
    star: <AiFillStar className="rating-star" />,
    reviews: "(286 reviews)",
    prevPrice: "$110,00",
    newPrice: "79",
    company: "Reebok",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71X7Q2ZMVBL._AC_UX575_.jpg",
    title: "Reebok Nano X3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(156 reviews)",
    prevPrice: "$140,00",
    newPrice: "99",
    company: "Reebok",
    color: "black",
    category: "training",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Y5X8QZKVL._AC_UX575_.jpg",
    title: "Reebok Zig Kinetica",
    star: <AiFillStar className="rating-star" />,
    reviews: "(167 reviews)",
    prevPrice: "$135,00",
    newPrice: "95",
    company: "Reebok",
    color: "green",
    category: "training",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Z8Q5XMVBL._AC_UX575_.jpg",
    title: "Reebok Flexagon Energy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(143 reviews)",
    prevPrice: "$90,00",
    newPrice: "65",
    company: "Reebok",
    color: "grey",
    category: "training",
  },
  {
    img: "https://m.media-amazon.com/images/I/71A7Q2XZKVL._AC_UX575_.jpg",
    title: "Reebok Workout Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(319 reviews)",
    prevPrice: "$100,00",
    newPrice: "69",
    company: "Reebok",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71B5X8QZMVL._AC_UX575_.jpg",
    title: "Reebok Royal Complete",
    star: <AiFillStar className="rating-star" />,
    reviews: "(194 reviews)",
    prevPrice: "$85,00",
    newPrice: "59",
    company: "Reebok",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71C8Q5XKZBL._AC_UX575_.jpg",
    title: "Reebok Energen Lite",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "$80,00",
    newPrice: "55",
    company: "Reebok",
    color: "blue",
    category: "running",
  },

  {
    img: "https://m.media-amazon.com/images/I/71D7Q2XMVBL._AC_UX575_.jpg",
    title: "Vans Old Skool",
    star: <AiFillStar className="rating-star" />,
    reviews: "(521 reviews)",
    prevPrice: "$90,00",
    newPrice: "65",
    company: "Vans",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E5X8QZKVL._AC_UX575_.jpg",
    title: "Vans Authentic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(451 reviews)",
    prevPrice: "$80,00",
    newPrice: "59",
    company: "Vans",
    color: "white",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71F8Q5XMVBL._AC_UX575_.jpg",
    title: "Vans Sk8-Hi",
    star: <AiFillStar className="rating-star" />,
    reviews: "(389 reviews)",
    prevPrice: "$100,00",
    newPrice: "75",
    company: "Vans",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71G7Q2XKZVL._AC_UX575_.jpg",
    title: "Vans Era Classic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(174 reviews)",
    prevPrice: "$85,00",
    newPrice: "62",
    company: "Vans",
    color: "navy",
    category: "casual",
  },

  {
    img: "https://m.media-amazon.com/images/I/71H5X8QZMVL._AC_UX575_.jpg",
    title: "ASICS Gel-Kayano 29",
    star: <AiFillStar className="rating-star" />,
    reviews: "(345 reviews)",
    prevPrice: "$180,00",
    newPrice: "129",
    company: "ASICS",
    color: "navy",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71J8Q5XKZBL._AC_UX575_.jpg",
    title: "ASICS Gel-Nimbus 25",
    star: <AiFillStar className="rating-star" />,
    reviews: "(421 reviews)",
    prevPrice: "$190,00",
    newPrice: "139",
    company: "ASICS",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71K7Q2XMVBL._AC_UX575_.jpg",
    title: "ASICS Gel-Contend 8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(278 reviews)",
    prevPrice: "$90,00",
    newPrice: "65",
    company: "ASICS",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71L5X8QZKBL._AC_UX575_.jpg",
    title: "ASICS Novablast 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(302 reviews)",
    prevPrice: "$160,00",
    newPrice: "119",
    company: "ASICS",
    color: "white",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71M8Q5XMVBL._AC_UX575_.jpg",
    title: "ASICS GT-1000 11",
    star: <AiFillStar className="rating-star" />,
    reviews: "(224 reviews)",
    prevPrice: "$130,00",
    newPrice: "95",
    company: "ASICS",
    color: "orange",
    category: "running",
  },

  {
    img: "https://m.media-amazon.com/images/I/71N7Q2XKZVL._AC_UX575_.jpg",
    title: "Skechers Go Run Consistent",
    star: <AiFillStar className="rating-star" />,
    reviews: "(276 reviews)",
    prevPrice: "$90,00",
    newPrice: "65",
    company: "Skechers",
    color: "blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71P5X8QZMVL._AC_UX575_.jpg",
    title: "Skechers Arch Fit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(367 reviews)",
    prevPrice: "$110,00",
    newPrice: "79",
    company: "Skechers",
    color: "grey",
    category: "walking",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Q8X5KZBL._AC_UX575_.jpg",
    title: "Skechers Max Cushioning",
    star: <AiFillStar className="rating-star" />,
    reviews: "(329 reviews)",
    prevPrice: "$120,00",
    newPrice: "89",
    company: "Skechers",
    color: "navy",
    category: "walking",
  },
  {
    img: "https://m.media-amazon.com/images/I/71R7Q2XMVBL._AC_UX575_.jpg",
    title: "Skechers Go Walk 6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(538 reviews)",
    prevPrice: "$100,00",
    newPrice: "72",
    company: "Skechers",
    color: "black",
    category: "walking",
  },

  {
    img: "https://m.media-amazon.com/images/I/71S5X8QZKVL._AC_UX575_.jpg",
    title: "Under Armour Charged Assert",
    star: <AiFillStar className="rating-star" />,
    reviews: "(189 reviews)",
    prevPrice: "$100,00",
    newPrice: "69",
    company: "Under Armour",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71T8Q5XMVBL._AC_UX575_.jpg",
    title: "Under Armour HOVR Phantom",
    star: <AiFillStar className="rating-star" />,
    reviews: "(218 reviews)",
    prevPrice: "$170,00",
    newPrice: "119",
    company: "Under Armour",
    color: "black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71V7Q2XKZVL._AC_UX575_.jpg",
    title: "Under Armour Charged Pursuit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(192 reviews)",
    prevPrice: "$90,00",
    newPrice: "62",
    company: "Under Armour",
    color: "grey",
    category: "running",
  },

  {
    img: "https://m.media-amazon.com/images/I/71W5X8QZMVL._AC_UX575_.jpg",
    title: "Converse Chuck Taylor All Star",
    star: <AiFillStar className="rating-star" />,
    reviews: "(634 reviews)",
    prevPrice: "$85,00",
    newPrice: "59",
    company: "Converse",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71X8Q5KZBL._AC_UX575_.jpg",
    title: "Converse Chuck 70",
    star: <AiFillStar className="rating-star" />,
    reviews: "(617 reviews)",
    prevPrice: "$110,00",
    newPrice: "79",
    company: "Converse",
    color: "black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Y7Q2XMVBL._AC_UX575_.jpg",
    title: "Converse Run Star Hike",
    star: <AiFillStar className="rating-star" />,
    reviews: "(273 reviews)",
    prevPrice: "$120,00",
    newPrice: "89",
    company: "Converse",
    color: "cream",
    category: "sneakers",
  },
];

export default data;
